# -*- coding: utf-8 -*-
"""Activitat1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p1kvKfzI9r0wEIlf1d8BxqU1TFMZ-Dwp
"""

#Exercici 1

import numpy as np

arraydeprova = np.array(([1,2,3], [3,2,1]), dtype=float)

# Funció

def funcio1(x):
  if x.ndim == 1:
    print('La dimensió és:', x.ndim, ". La longitud de l'array és:", len(x), ". Hi ha ", x.size, "elements en l'array")
  else:
    print('Hi ha hagut un error en la dimensió')

print(funcio1(arraydeprova))

#Exercici 2
def quadrat(a):
  a = np.random.rand(2,2)
  print(a)

print(quadrat(a))

#Exercici 3

prova=np.array([(1,2,3), (4,5,6)], dtype=float)
print(prova)

def calcul(x):
  for column in prova:
    print("La suma dels valors de les columnes donen", np.sum(x,axis=1))

print(calcul(prova))

#Exercici 4

def corr(z):
  print(np.corrcoef(z))

print(corr(prova))

prova2= np.array([(34,65,32), (213,231,3)], dtype=float)

print(corr(prova2))